import { Vehicle, Driver, Trip, StopReport, BreakdownReport, AlertRule, NotificationItem, ExternalApiData } from '../types';

export const INITIAL_VEHICLES: Vehicle[] = [
  {
    id: 'veh_car_01',
    plate: 'LD-44-88-HA',
    model: 'Corolla 1.8 Dual VVT-i',
    brand: 'Toyota',
    year: 2022,
    type: 'car_taxi',
    color: 'Branco Pérola / Azul Táxi',
    status: 'in_trip',
    driverId: 'drv_01',
    driverName: 'Mateus Kipupa',
    fuelLevel: 68,
    fuelType: 'gasoline',
    oilHealth: 84,
    odometerKm: 74230,
    batteryLevel: 94,
    engineTempC: 88,
    tirePressureBar: 2.3,
    speedKmH: 42,
    coordinates: {
      lat: -8.8383,
      lng: 13.2344,
      heading: 145,
      address: 'Avenida 4 de Fevereiro, Marginal de Luanda',
    },
    lastMaintenanceDate: '2025-01-10',
    nextMaintenanceKm: 80000,
    activeIssuesCount: 0,
    qrCode: 'QR-VEH-CAR-01',
  },
  {
    id: 'veh_moto_01',
    plate: 'LD-92-11-MX',
    model: 'Boxer 150 HD',
    brand: 'Bajaj',
    year: 2023,
    type: 'moto_taxi',
    color: 'Vermelho Fogo',
    status: 'in_trip',
    driverId: 'drv_02',
    driverName: 'António João Kambuta',
    fuelLevel: 45,
    fuelType: 'gasoline',
    oilHealth: 62,
    odometerKm: 28410,
    batteryLevel: 89,
    engineTempC: 76,
    tirePressureBar: 2.1,
    speedKmH: 38,
    coordinates: {
      lat: -8.8159,
      lng: 13.2422,
      heading: 210,
      address: 'Rua Rainha Ginga, Maianga',
    },
    lastMaintenanceDate: '2025-01-28',
    nextMaintenanceKm: 30000,
    activeIssuesCount: 0,
    qrCode: 'QR-VEH-MOTO-01',
  },
  {
    id: 'veh_car_02',
    plate: 'LD-12-99-GB',
    model: 'Accent 1.6 Sedan',
    brand: 'Hyundai',
    year: 2021,
    type: 'car_taxi',
    color: 'Prata Metálico',
    status: 'stopped',
    driverId: 'drv_03',
    driverName: 'Domingos Sebastião',
    fuelLevel: 14, // LOW FUEL ALERT!
    fuelType: 'gasoline',
    oilHealth: 28, // OIL WARNING!
    odometerKm: 98120,
    batteryLevel: 78,
    engineTempC: 92,
    tirePressureBar: 2.0,
    speedKmH: 0,
    coordinates: {
      lat: -8.8450,
      lng: 13.2510,
      heading: 0,
      address: 'Posto Sonangol, Avenida Deolinda Rodrigues',
    },
    lastMaintenanceDate: '2024-11-20',
    nextMaintenanceKm: 100000,
    activeIssuesCount: 1,
    qrCode: 'QR-VEH-CAR-02',
  },
  {
    id: 'veh_moto_02',
    plate: 'LD-33-04-TR',
    model: 'Apache RTR 160',
    brand: 'TVS',
    year: 2024,
    type: 'moto_taxi',
    color: 'Preto & Amarelo',
    status: 'idle',
    driverId: 'drv_04',
    driverName: 'Sebastião Pedro Luveba',
    fuelLevel: 82,
    fuelType: 'gasoline',
    oilHealth: 92,
    odometerKm: 14500,
    batteryLevel: 98,
    engineTempC: 65,
    tirePressureBar: 2.2,
    speedKmH: 0,
    coordinates: {
      lat: -8.8290,
      lng: 13.2280,
      heading: 90,
      address: 'Largo do Kinaxixi, Centro',
    },
    lastMaintenanceDate: '2025-02-05',
    nextMaintenanceKm: 18000,
    activeIssuesCount: 0,
    qrCode: 'QR-VEH-MOTO-02',
  },
  {
    id: 'veh_car_03',
    plate: 'LD-78-45-KC',
    model: 'Dzire GL 1.2',
    brand: 'Suzuki',
    year: 2023,
    type: 'car_taxi',
    color: 'Branco Glacial',
    status: 'in_trip',
    driverId: 'drv_05',
    driverName: 'Manuel Afonso Neto',
    fuelLevel: 52,
    fuelType: 'gasoline',
    oilHealth: 75,
    odometerKm: 51200,
    batteryLevel: 91,
    engineTempC: 86,
    tirePressureBar: 2.3,
    speedKmH: 48,
    coordinates: {
      lat: -8.8680,
      lng: 13.2620,
      heading: 180,
      address: 'Via Expressa Fidel Castro, Talatona',
    },
    lastMaintenanceDate: '2025-01-18',
    nextMaintenanceKm: 55000,
    activeIssuesCount: 0,
    qrCode: 'QR-VEH-CAR-03',
  },
  {
    id: 'veh_moto_03',
    plate: 'LD-55-77-HP',
    model: 'HJ 110-2D Lucky',
    brand: 'Haojue',
    year: 2022,
    type: 'moto_taxi',
    color: 'Azul Celeste',
    status: 'critical_breakdown',
    driverId: 'drv_06',
    driverName: 'Francisco Zua',
    fuelLevel: 30,
    fuelType: 'gasoline',
    oilHealth: 15, // CRITICAL OIL!
    odometerKm: 42100,
    batteryLevel: 45,
    engineTempC: 104, // OVERHEATING
    tirePressureBar: 1.6,
    speedKmH: 0,
    coordinates: {
      lat: -8.8520,
      lng: 13.2840,
      heading: 0,
      address: 'Rotunda da Samba, Luanda Sul',
    },
    lastMaintenanceDate: '2024-10-14',
    nextMaintenanceKm: 43000,
    activeIssuesCount: 2,
    qrCode: 'QR-VEH-MOTO-03',
  },
  {
    id: 'veh_car_04',
    plate: 'LD-90-12-AE',
    model: 'Starlet 1.4 Dynamic',
    brand: 'Toyota',
    year: 2023,
    type: 'car_taxi',
    color: 'Cinzento Grafite',
    status: 'idle',
    driverId: 'drv_07',
    driverName: 'Valdemar Costa',
    fuelLevel: 90,
    fuelType: 'gasoline',
    oilHealth: 88,
    odometerKm: 33400,
    batteryLevel: 96,
    engineTempC: 70,
    tirePressureBar: 2.3,
    speedKmH: 0,
    coordinates: {
      lat: -8.8120,
      lng: 13.2380,
      heading: 45,
      address: 'Aeroporto Internacional 4 de Fevereiro',
    },
    lastMaintenanceDate: '2025-02-01',
    nextMaintenanceKm: 40000,
    activeIssuesCount: 0,
    qrCode: 'QR-VEH-CAR-04',
  }
];

export const INITIAL_DRIVERS: Driver[] = [
  {
    id: 'drv_01',
    name: 'Mateus Kipupa',
    phone: '+244 923 881 229',
    email: 'mateus.kipupa@fleetgo.co',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=256',
    status: 'busy',
    vehicleType: 'car_taxi',
    assignedVehicleId: 'veh_car_01',
    assignedVehiclePlate: 'LD-44-88-HA',
    licenseNumber: 'CNH-AO-994821',
    licenseCategory: 'B (Profissional)',
    licenseExpiry: '2027-08-15',
    rating: 4.92,
    totalTripsCount: 1420,
    totalEarningsAOA: 2840000,
    shiftHoursActive: 5.4,
    fatigueWarning: false,
    joinedDate: '2023-04-12',
    emergencyContact: 'Teresa Kipupa (+244 912 334 111)',
    documentsVerified: true,
  },
  {
    id: 'drv_02',
    name: 'António João Kambuta',
    phone: '+244 944 112 390',
    email: 'antonio.kambuta@fleetgo.co',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=256',
    status: 'busy',
    vehicleType: 'moto_taxi',
    assignedVehicleId: 'veh_moto_01',
    assignedVehiclePlate: 'LD-92-11-MX',
    licenseNumber: 'CNH-AO-331092',
    licenseCategory: 'A (Moto-Táxi)',
    licenseExpiry: '2026-11-20',
    rating: 4.88,
    totalTripsCount: 2150,
    totalEarningsAOA: 2150000,
    shiftHoursActive: 7.2,
    fatigueWarning: true, // FATIGUE WARNING
    joinedDate: '2023-01-05',
    emergencyContact: 'Rosa Kambuta (+244 931 990 882)',
    documentsVerified: true,
  },
  {
    id: 'drv_03',
    name: 'Domingos Sebastião',
    phone: '+244 912 776 543',
    email: 'domingos.sebastiao@fleetgo.co',
    avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&q=80&w=256',
    status: 'on_break',
    vehicleType: 'car_taxi',
    assignedVehicleId: 'veh_car_02',
    assignedVehiclePlate: 'LD-12-99-GB',
    licenseNumber: 'CNH-AO-778812',
    licenseCategory: 'B (Profissional)',
    licenseExpiry: '2028-02-10',
    rating: 4.75,
    totalTripsCount: 890,
    totalEarningsAOA: 1780000,
    shiftHoursActive: 4.0,
    fatigueWarning: false,
    joinedDate: '2023-09-18',
    emergencyContact: 'Maria Sebastião (+244 923 112 443)',
    documentsVerified: true,
  },
  {
    id: 'drv_04',
    name: 'Sebastião Pedro Luveba',
    phone: '+244 933 665 442',
    email: 'sebastiao.luveba@fleetgo.co',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&q=80&w=256',
    status: 'online',
    vehicleType: 'moto_taxi',
    assignedVehicleId: 'veh_moto_02',
    assignedVehiclePlate: 'LD-33-04-TR',
    licenseNumber: 'CNH-AO-551199',
    licenseCategory: 'A (Moto-Táxi)',
    licenseExpiry: '2027-05-19',
    rating: 4.95,
    totalTripsCount: 1680,
    totalEarningsAOA: 1680000,
    shiftHoursActive: 2.5,
    fatigueWarning: false,
    joinedDate: '2024-02-11',
    emergencyContact: 'Irene Luveba (+244 944 887 665)',
    documentsVerified: true,
  },
  {
    id: 'drv_05',
    name: 'Manuel Afonso Neto',
    phone: '+244 928 443 219',
    email: 'manuel.neto@fleetgo.co',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=256',
    status: 'busy',
    vehicleType: 'car_taxi',
    assignedVehicleId: 'veh_car_03',
    assignedVehiclePlate: 'LD-78-45-KC',
    licenseNumber: 'CNH-AO-664422',
    licenseCategory: 'B (Profissional)',
    licenseExpiry: '2026-09-30',
    rating: 4.86,
    totalTripsCount: 1120,
    totalEarningsAOA: 2240000,
    shiftHoursActive: 6.1,
    fatigueWarning: false,
    joinedDate: '2023-06-20',
    emergencyContact: 'Paula Neto (+244 912 009 887)',
    documentsVerified: true,
  },
  {
    id: 'drv_06',
    name: 'Francisco Zua',
    phone: '+244 949 332 101',
    email: 'francisco.zua@fleetgo.co',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=256',
    status: 'suspended',
    vehicleType: 'moto_taxi',
    assignedVehicleId: 'veh_moto_03',
    assignedVehiclePlate: 'LD-55-77-HP',
    licenseNumber: 'CNH-AO-112233',
    licenseCategory: 'A',
    licenseExpiry: '2025-12-01',
    rating: 4.60,
    totalTripsCount: 740,
    totalEarningsAOA: 740000,
    shiftHoursActive: 8.5,
    fatigueWarning: true,
    joinedDate: '2024-05-03',
    emergencyContact: 'Juliana Zua (+244 923 776 554)',
    documentsVerified: true,
  },
  {
    id: 'drv_07',
    name: 'Valdemar Costa',
    phone: '+244 911 223 998',
    email: 'valdemar.costa@fleetgo.co',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=256',
    status: 'online',
    vehicleType: 'car_taxi',
    assignedVehicleId: 'veh_car_04',
    assignedVehiclePlate: 'LD-90-12-AE',
    licenseNumber: 'CNH-AO-889900',
    licenseCategory: 'B (Profissional)',
    licenseExpiry: '2027-03-25',
    rating: 4.98,
    totalTripsCount: 1980,
    totalEarningsAOA: 3960000,
    shiftHoursActive: 1.8,
    fatigueWarning: false,
    joinedDate: '2022-11-15',
    emergencyContact: 'Carla Costa (+244 922 445 667)',
    documentsVerified: true,
  }
];

export const INITIAL_TRIPS: Trip[] = [
  {
    id: 'trip_1001',
    tripNumber: 'CR-2025-8821',
    passengerName: 'Engª. Beatriz Vunge',
    passengerPhone: '+244 923 119 004',
    driverId: 'drv_01',
    driverName: 'Mateus Kipupa',
    vehicleId: 'veh_car_01',
    vehiclePlate: 'LD-44-88-HA',
    vehicleType: 'car_taxi',
    origin: {
      address: 'Aeroporto Internacional 4 de Fevereiro',
      lat: -8.8583,
      lng: 13.2310,
    },
    destination: {
      address: 'Hotel Epic Sana, Avenida Lenine, Luanda',
      lat: -8.8210,
      lng: 13.2380,
    },
    distanceKm: 8.4,
    estimatedDurationMinutes: 24,
    actualDurationMinutes: 22,
    fareAOA: 4500,
    fareCurrency: 'AOA',
    paymentMethod: 'multicaixa_express',
    status: 'in_progress',
    startTime: '2025-08-16T12:35:00Z',
    rating: 5,
  },
  {
    id: 'trip_1002',
    tripNumber: 'CR-2025-8822',
    passengerName: 'Dra. Sandra Cassule',
    passengerPhone: '+244 912 884 110',
    driverId: 'drv_02',
    driverName: 'António João Kambuta',
    vehicleId: 'veh_moto_01',
    vehiclePlate: 'LD-92-11-MX',
    vehicleType: 'moto_taxi',
    origin: {
      address: 'Mercado dos Congolenses, Rangel',
      lat: -8.8350,
      lng: 13.2650,
    },
    destination: {
      address: 'Ministério das Finanças, Mutamba',
      lat: -8.8140,
      lng: 13.2320,
    },
    distanceKm: 4.8,
    estimatedDurationMinutes: 14,
    fareAOA: 1500,
    fareCurrency: 'AOA',
    paymentMethod: 'cash',
    status: 'in_progress',
    startTime: '2025-08-16T12:45:00Z',
  },
  {
    id: 'trip_1003',
    tripNumber: 'CR-2025-8823',
    passengerName: 'Dr. Paulo Gaspar',
    passengerPhone: '+244 944 221 990',
    driverId: 'drv_05',
    driverName: 'Manuel Afonso Neto',
    vehicleId: 'veh_car_03',
    vehiclePlate: 'LD-78-45-KC',
    vehicleType: 'car_taxi',
    origin: {
      address: 'Belas Shopping, Talatona',
      lat: -8.9100,
      lng: 13.1850,
    },
    destination: {
      address: 'Porto de Luanda, Baía',
      lat: -8.8080,
      lng: 13.2450,
    },
    distanceKm: 16.5,
    estimatedDurationMinutes: 38,
    fareAOA: 8500,
    fareCurrency: 'AOA',
    paymentMethod: 'multicaixa_express',
    status: 'in_progress',
    startTime: '2025-08-16T12:20:00Z',
  },
  {
    id: 'trip_1004',
    tripNumber: 'CR-2025-8820',
    passengerName: 'Mariana Fernandes',
    passengerPhone: '+244 928 334 119',
    driverId: 'drv_07',
    driverName: 'Valdemar Costa',
    vehicleId: 'veh_car_04',
    vehiclePlate: 'LD-90-12-AE',
    vehicleType: 'car_taxi',
    origin: {
      address: 'Condomínio Dolce Vita, Talatona',
      lat: -8.9210,
      lng: 13.1920,
    },
    destination: {
      address: 'Hospital Américo Boavida, Rangel',
      lat: -8.8310,
      lng: 13.2590,
    },
    distanceKm: 14.2,
    estimatedDurationMinutes: 32,
    actualDurationMinutes: 30,
    fareAOA: 7200,
    fareCurrency: 'AOA',
    paymentMethod: 'card',
    status: 'completed',
    startTime: '2025-08-16T11:00:00Z',
    endTime: '2025-08-16T11:30:00Z',
    rating: 5,
  },
  {
    id: 'trip_1005',
    tripNumber: 'CR-2025-8819',
    passengerName: 'Joaquim Luvualu',
    passengerPhone: '+244 931 009 224',
    driverId: 'drv_04',
    driverName: 'Sebastião Pedro Luveba',
    vehicleId: 'veh_moto_02',
    vehiclePlate: 'LD-33-04-TR',
    vehicleType: 'moto_taxi',
    origin: {
      address: 'Largo 1º de Maio',
      lat: -8.8280,
      lng: 13.2410,
    },
    destination: {
      address: 'Campus Universitário UAN, Camama',
      lat: -8.9320,
      lng: 13.2780,
    },
    distanceKm: 12.0,
    estimatedDurationMinutes: 25,
    actualDurationMinutes: 24,
    fareAOA: 2500,
    fareCurrency: 'AOA',
    paymentMethod: 'cash',
    status: 'completed',
    startTime: '2025-08-16T10:15:00Z',
    endTime: '2025-08-16T10:39:00Z',
    rating: 5,
  }
];

export const INITIAL_STOP_REPORTS: StopReport[] = [
  {
    id: 'stp_001',
    vehicleId: 'veh_car_02',
    vehiclePlate: 'LD-12-99-GB',
    vehicleType: 'car_taxi',
    driverId: 'drv_03',
    driverName: 'Domingos Sebastião',
    reason: 'fueling',
    description: 'Paragem para reabastecimento completo de gasolina (45 litros) e calibração de pneus.',
    startedAt: '2025-08-16T12:15:00Z',
    expectedDurationMinutes: 20,
    actualDurationMinutes: 18,
    location: {
      address: 'Posto Sonangol, Avenida Deolinda Rodrigues',
      lat: -8.8450,
      lng: 13.2510,
    },
    photos: [
      'https://images.unsplash.com/photo-1527018607619-a508a2be00bf?auto=format&fit=crop&q=80&w=600',
      'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&q=80&w=600'
    ],
    audioMemoUrl: 'simulated_audio_rec_fuel_stp001.mp3',
    audioDurationSec: 24,
    odometerKmAtStop: 98120,
    fuelLitresAdded: 45,
    fuelCostAOA: 13500,
    status: 'approved',
    reviewedBy: 'Carlos Alberto Silva (Admin)',
    reviewNotes: 'Recibo conferido e aprovado no sistema de tesouraria.',
    timestamp: '2025-08-16T12:20:00Z',
  },
  {
    id: 'stp_002',
    vehicleId: 'veh_moto_01',
    vehiclePlate: 'LD-92-11-MX',
    vehicleType: 'moto_taxi',
    driverId: 'drv_02',
    driverName: 'António João Kambuta',
    reason: 'police_inspection',
    description: 'Paragem obrigatória em operação de trânsito da Polícia Nacional (DNVT). Verificação de capacetes, colete reflector e licença de moto-táxi regular.',
    startedAt: '2025-08-16T09:40:00Z',
    expectedDurationMinutes: 15,
    actualDurationMinutes: 12,
    location: {
      address: 'Rotunda do Camama, Luanda',
      lat: -8.9050,
      lng: 13.2450,
    },
    photos: [
      'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&q=80&w=600'
    ],
    audioMemoUrl: 'simulated_audio_blitz_dnvt.mp3',
    audioDurationSec: 18,
    odometerKmAtStop: 28390,
    status: 'approved',
    reviewedBy: 'Helena Mendes (Gestora)',
    reviewNotes: 'Documentação validada sem autuações.',
    timestamp: '2025-08-16T09:55:00Z',
  },
  {
    id: 'stp_003',
    vehicleId: 'veh_moto_03',
    vehiclePlate: 'LD-55-77-HP',
    vehicleType: 'moto_taxi',
    driverId: 'drv_06',
    driverName: 'Francisco Zua',
    reason: 'mechanical_check',
    description: 'Paragem de emergência na berma devido a ruído anormal na corrente de transmissão e luz de óleo intermitente.',
    startedAt: '2025-08-16T11:45:00Z',
    expectedDurationMinutes: 45,
    location: {
      address: 'Rotunda da Samba, Luanda Sul',
      lat: -8.8520,
      lng: 13.2840,
    },
    photos: [
      'https://images.unsplash.com/photo-1486006920555-c77dce18193b?auto=format&fit=crop&q=80&w=600'
    ],
    audioMemoUrl: 'simulated_voice_avaria_urgente.mp3',
    audioDurationSec: 42,
    odometerKmAtStop: 42100,
    status: 'pending_review',
    timestamp: '2025-08-16T11:50:00Z',
  }
];

export const INITIAL_BREAKDOWN_REPORTS: BreakdownReport[] = [
  {
    id: 'brk_101',
    vehicleId: 'veh_moto_03',
    vehiclePlate: 'LD-55-77-HP',
    vehicleType: 'moto_taxi',
    driverId: 'drv_06',
    driverName: 'Francisco Zua',
    title: 'Superaquecimento de Motor & Nível Crítico de Óleo',
    description: 'Motor aqueceu excessivamente com fumo ligeiro no cárter e desgaste da corrente de transmissão. Moto imobilizada.',
    category: 'engine',
    severity: 'critical',
    status: 'in_workshop',
    photos: [
      'https://images.unsplash.com/photo-1486006920555-c77dce18193b?auto=format&fit=crop&q=80&w=600'
    ],
    audioMemoUrl: 'audio_mecanico_diagnostico.mp3',
    estimatedCostAOA: 85000,
    workshopName: 'Oficina Central MotoTech Samba',
    mechanicName: 'Mestre Bernardo Kiala',
    partsNeeded: ['Kit de Juntas', 'Óleo 20W50 4T (2L)', 'Corrente 428H D.I.D', 'Vela de Ignição NGK'],
    reportedAt: '2025-08-16T11:50:00Z',
    estimatedResolutionDate: '2025-08-17T17:00:00Z',
    impactOnTrip: true,
  },
  {
    id: 'brk_102',
    vehicleId: 'veh_car_02',
    vehiclePlate: 'LD-12-99-GB',
    vehicleType: 'car_taxi',
    driverId: 'drv_03',
    driverName: 'Domingos Sebastião',
    title: 'Desgaste Excessivo de Pastilhas de Travão Dianteiras',
    description: 'Ruído metálico ao travar a mais de 40 km/h. Sinal de pastilhas no limite de segurança.',
    category: 'brakes',
    severity: 'medium',
    status: 'diagnosing',
    photos: [
      'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&q=80&w=600'
    ],
    estimatedCostAOA: 42000,
    workshopName: 'AutoBox Express Luanda',
    mechanicName: 'Eng. Paulo Andrade',
    partsNeeded: ['Jogo de Pastilhas Dianteiras Hyundai Accent', 'Fluido de Travão DOT4'],
    reportedAt: '2025-08-15T16:30:00Z',
    estimatedResolutionDate: '2025-08-16T18:00:00Z',
    impactOnTrip: false,
  }
];

export const INITIAL_ALERT_RULES: AlertRule[] = [
  {
    id: 'rule_oil',
    name: 'Saúde do Óleo Abaixo de 20%',
    enabled: true,
    conditionType: 'oil_below',
    thresholdValue: 20,
    unit: '%',
    severity: 'critical',
    notifySound: true,
  },
  {
    id: 'rule_fuel',
    name: 'Combustível na Reserva (< 15%)',
    enabled: true,
    conditionType: 'fuel_below',
    thresholdValue: 15,
    unit: '%',
    severity: 'warning',
    notifySound: true,
  },
  {
    id: 'rule_stop',
    name: 'Paragem Não Autorizada (> 30 min)',
    enabled: true,
    conditionType: 'stop_exceeded',
    thresholdValue: 30,
    unit: 'min',
    severity: 'warning',
    notifySound: false,
  },
  {
    id: 'rule_speed',
    name: 'Excesso de Velocidade (> 80 km/h)',
    enabled: true,
    conditionType: 'speed_exceeded',
    thresholdValue: 80,
    unit: 'km/h',
    severity: 'critical',
    notifySound: true,
  },
  {
    id: 'rule_temp',
    name: 'Superaquecimento de Motor (> 98°C)',
    enabled: true,
    conditionType: 'temp_exceeded',
    thresholdValue: 98,
    unit: '°C',
    severity: 'critical',
    notifySound: true,
  }
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif_01',
    title: 'Superaquecimento Crítico no Veículo LD-55-77-HP',
    message: 'Moto-táxi de Francisco Zua atingiu 104°C e óleo a 15%. Veículo parado na Samba.',
    severity: 'critical',
    timestamp: '2025-08-16T11:51:00Z',
    read: false,
    vehicleId: 'veh_moto_03',
    vehiclePlate: 'LD-55-77-HP',
    driverId: 'drv_06',
    category: 'telemetry',
  },
  {
    id: 'notif_02',
    title: 'Combustível na Reserva: Táxi LD-12-99-GB',
    message: 'Nível de gasolina atingiu 14%. Motorista Domingos Sebastião iniciou paragem em posto.',
    severity: 'warning',
    timestamp: '2025-08-16T12:14:00Z',
    read: false,
    vehicleId: 'veh_car_02',
    vehiclePlate: 'LD-12-99-GB',
    driverId: 'drv_03',
    category: 'stop_report',
  },
  {
    id: 'notif_03',
    title: 'Alerta de Fadiga do Motorista',
    message: 'António João Kambuta completou 7.2 horas contínuas de condução de moto-táxi. Recomendada pausa.',
    severity: 'warning',
    timestamp: '2025-08-16T12:00:00Z',
    read: false,
    driverId: 'drv_02',
    category: 'telemetry',
  },
  {
    id: 'notif_04',
    title: 'Corrida de Alto Valor Concluída',
    message: 'Corrida CR-2025-8820 no valor de 7.200 Kz paga via Cartão por Mariana Fernandes.',
    severity: 'success',
    timestamp: '2025-08-16T11:31:00Z',
    read: true,
    category: 'trip',
  }
];

export const INITIAL_EXTERNAL_API_DATA: ExternalApiData = {
  weather: {
    city: 'Luanda, Angola',
    temperatureC: 29,
    condition: 'Ensolarado',
    humidityPercent: 68,
    windSpeedKmH: 18,
    roadConditionAlert: 'Pistas secas e excelente visibilidade.',
  },
  fuelPriceIndex: {
    gasolineAOA: 300, // Preço oficial por litro em Kz
    dieselAOA: 200,
    trend: 'stable',
    lastUpdated: '2025-08-16T06:00:00Z',
  },
  trafficIndex: {
    status: 'Moderado',
    averageSpeedCityKmH: 26.5,
    congestedZones: ['Avenida Deolinda Rodrigues', 'Largo 1º de Maio', 'Rotunda da Samba'],
  },
};
